---
title: "Sprint#02: Ways towards A Net-Zero Society, Take NYC as an Example"
date: "2023-04-21"
output: pdf_document
---
```{r}
Sys.setenv('R_MAX_VSIZE'=32000000000)
library(tidyverse)
library(modelr)
```
```{r}
file_path <- file.path(dirname(rstudioapi::getSourceEditorContext()$path), "dataset/nyc_eui_census.csv")
raw_data <- read_csv(file_path)
eui_bg <- as_tibble(raw_data)  %>%
  filter(buildingType == "Multifamily Housing" |
         buildingType == "Office" |
         buildingType == "Hotel" |
         buildingType == "Senior Care Community" |
         buildingType == "Non-Refrigerated Warehouse" |
         buildingType == "Residence Hall/Dormitory") %>%
  filter(WN_EUI > 0) %>%
  filter(WN_EUI < 500) %>%
  na.omit()
sort(eui_bg$WN_EUI, decreasing = TRUE)
```
```{r}
library(lattice)
library(reshape2)

# calculate correlation matrix
cor_matrix <- cor(eui_bg[,c("WN_EUI", 
                             "GHG", 
                             "buildingAge",
                             "area",
                             "income", 
                             "higherEduRate", 
                             "marriageRate",
                             "commuteTime",
                             "liveAloneRate",
                             "maleRate",
                             "avgAge")])

corr_mel <- melt(cor_matrix)
corr_mel

library(corrplot)
corrplot(cor_matrix,method="color")
```

```{r}
# eui vs income
eui_bg_fil <- eui_bg %>%
  select(income, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ income * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(income, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = income, y = WN_EUI, color = buildingType), size = 0.2, alpha = 0.4) +
  geom_line(data = lm1_data, aes(x = income, y = pred, color = buildingType)) +
  labs(x = "income", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs income") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ income * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(income, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = income, y = log(WN_EUI), color = buildingType), size = 0.2, alpha = 0.4) +
  geom_line(data = lm2_data, aes(x = income, y = pred, color = buildingType)) +
  labs(x = "income", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs income") +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
# eui vs education
eui_bg_fil <- eui_bg %>%
  select(higherEduRate, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ higherEduRate * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(higherEduRate, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = higherEduRate, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = higherEduRate, y = pred, color = buildingType)) +
  labs(x = "higher Eduation Rate", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs higherEduRate") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ higherEduRate * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(higherEduRate, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = higherEduRate, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = higherEduRate, y = pred, color = buildingType)) +
  labs(x = "higher Eduation Rate", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs higherEduRate") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
# eui vs marriage rate
eui_bg_fil <- eui_bg %>%
  select(marriageRate, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ marriageRate * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(marriageRate, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = marriageRate, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = marriageRate, y = pred, color = buildingType)) +
  labs(x = "marriage Rate(%)", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs marriageRate") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ marriageRate * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(marriageRate, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = marriageRate, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = marriageRate, y = pred, color = buildingType)) +
  labs(x = "marriage Rate(%)", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs marriageRate") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```


```{r}
# eui vs commute time
eui_bg_fil <- eui_bg %>%
  select(commuteTime, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ commuteTime * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(commuteTime, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = commuteTime, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = commuteTime, y = pred, color = buildingType)) +
  labs(x = "commute Time(min)", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs commuteTime") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ commuteTime * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(commuteTime, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = commuteTime, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = commuteTime, y = pred, color = buildingType)) +
  labs(x = "commute Time(min)", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs commuteTime") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# eui vs live alone rate
eui_bg_fil <- eui_bg %>%
  select(liveAloneRate, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ liveAloneRate * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(liveAloneRate, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = liveAloneRate, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = liveAloneRate, y = pred, color = buildingType)) +
  labs(x = "live Alone Rate(%)", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs liveAloneRate") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ liveAloneRate * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(liveAloneRate, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = liveAloneRate, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = liveAloneRate, y = pred, color = buildingType)) +
  labs(x = "liveAloneRate(%)", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs liveAloneRate") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# eui vs male rate
eui_bg_fil <- eui_bg %>%
  select(maleRate, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ maleRate * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(maleRate, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = maleRate, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = maleRate, y = pred, color = buildingType)) +
  labs(x = "male Rate(%)", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs maleRate") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ maleRate * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(maleRate, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = maleRate, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = maleRate, y = pred, color = buildingType)) +
  labs(x = "male Rate(%)", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs maleRate") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# eui vs avgAge
eui_bg_fil <- eui_bg %>%
  select(avgAge, WN_EUI, buildingType)
# y ~ x
lm1 <- lm(WN_EUI ~ avgAge * buildingType, data = eui_bg_fil)
lm1_data <- eui_bg_fil %>%
  data_grid(avgAge, WN_EUI, buildingType) %>%
  add_predictions(lm1) %>%
  add_residuals(lm1)
lm1_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = avgAge, y = WN_EUI, color = buildingType), size = 0.2) +
  geom_line(data = lm1_data, aes(x = avgAge, y = pred, color = buildingType)) +
  labs(x = "average Age", y = "EUI(kBtu/sqft)", title = "Linear Regression of EUI vs avgAge") +
  theme(plot.title = element_text(hjust = 0.5))

```
```{r}
summary(lm1)
```

```{r}
# log(y) ~ x
lm2 <- lm(log(WN_EUI) ~ avgAge * buildingType, data = eui_bg_fil)
lm2_data <- eui_bg_fil %>%
  data_grid(avgAge, WN_EUI, buildingType) %>%
  add_predictions(lm2) %>%
  add_residuals(lm2)
lm2_data
ggplot(data = eui_bg_fil) +
  geom_point(aes(x = avgAge, y = log(WN_EUI), color = buildingType), size = 0.2) +
  geom_line(data = lm2_data, aes(x = avgAge, y = pred, color = buildingType)) +
  labs(x = "average Age", y = "log(EUI)(kBtu/sqft)", title = "Linear Regression of log(EUI) vs avgAge") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
lm <- lm(Site_EUI__ ~ higherEduRate * commuteTime * area * buildingAge * avgAge * liveAloneRate , data = eui_bg)
summary(lm)
```
```{R}
library(randomForest)
set.seed(42)
rf <- eui_bg %>%
  RandomForest(Site_EUI__ ~ income * commuteTime * area * buildingAge * avgAge, ntree=10, mtry=1)
summary(rf)
```